include $(THEOS)/makefiles/common.mk

TOOL_NAME = ramjetd
$(TOOL_NAME)_FILES = main.c
$(TOOL_NAME)_CFLAGS = -I../ 
$(TOOL_NAME)_CODESIGN_FLAGS = -Sentitlements.plist

include $(THEOS_MAKE_PATH)/tool.mk
