include $(THEOS)/makefiles/common.mk

TOOL_NAME = ramjetd
ramjetd_FILES = main.m
ramjetd_INSTALL_PATH = /usr/libexec
ramjetd_CFLAGS = -I../ 
ramjetd_CODESIGN_FLAGS = -Sentitlements.plist

include $(THEOS_MAKE_PATH)/tool.mk
